imports:
    - { resource: tables.yml }
services:
    dmzx.youtubegallery.controller:
        class: dmzx\youtubegallery\controller\youtubegallery
        arguments:
            - @config
            - @controller.helper
            - @template
            - @log
            - @user
            - @auth
            - @dbal.conn
            - @request
            - @pagination
            - %core.root_path%
            - %core.php_ext%
            - %dmzx.youtubegallery.table.video%
            - %dmzx.youtubegallery.table.video_cat%
            - %dmzx.youtubegallery.table.video_cmnts%
    dmzx.youtubegallery.admin.controller:
        class: dmzx\youtubegallery\controller\admin_controller
        arguments:
            - @config
            - @template
            - @log
            - @user
            - @dbal.conn
            - @request
            - %core.root_path%
            - %core.php_ext%
            - %dmzx.youtubegallery.table.video%
            - %dmzx.youtubegallery.table.video_cat%
    dmzx.youtubegallery.listener:
        class: dmzx\youtubegallery\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @dbal.conn
            - %dmzx.youtubegallery.table.video%
            - %dmzx.youtubegallery.table.video_cat%
            - %dmzx.youtubegallery.table.video_cmnts%
        tags:
            - { name: event.listener }
