services:
    dmzx.youtubegallery.controller:
        class: dmzx\youtubegallery\controller\youtubegallery
        arguments:
            - @dmzx.youtubegallery.render_helper
            - @controller.helper
            - @request
    dmzx.youtubegallery.functions_youtubegallery:
        class: dmzx\youtubegallery\core\functions_youtubegallery
        arguments:
            - @template
            - @user
            - @auth
            - @log
            - @dbal.conn
            - @cache
            - %core.table_prefix%
    dmzx.youtubegallery.render_helper:
        class: dmzx\youtubegallery\core\render_helper
        arguments:
            - @dmzx.youtubegallery.functions_youtubegallery
            - @config
            - @controller.helper
            - @template
            - @log
            - @user
            - @auth
            - @dbal.conn
            - @cache
            - @request
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%			
    dmzx.youtubegallery.listener:
        class: dmzx\youtubegallery\event\listener
        arguments:
            - @dmzx.youtubegallery.render_helper
            - @auth
            - @config
            - @controller.helper
            - @template
            - @user
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%			
        tags:
            - { name: event.listener }
